#!/bin/bash

grep_irn () {
   # TODO This will fail if given a relative path. Use readlink -f to
   # get full path of file.
    /usr/bin/grep -irn $@ | sed 's/.*:[0-9]\+/file:& /'
}

just_grep () {
    /usr/bin/grep $@
}

# This black magic is called "Shell Parameter Expansion"
# https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion
sanitized_args=${@//-eliad/ }

if [[ "$@" =~ "-eliad" ]]; then
    grep_irn $sanitized_args
else
    just_grep $sanitized_args
fi
