#!/bin/bash

grep_irn () {
   #echo "Running in grep_irn"
   #echo "$COMMAND"
   /usr/bin/grep -irn $COMMAND | sed 's/:/ +/'
}

just_grep () {
  #echo "In just_grep"
  #echo "$COMMAND"
  /usr/bin/grep $COMMAND
}

FLAGS=$1
case "${FLAGS}" in
  -eliad*) 
	  shift
          COMMAND=$@
	  grep_irn
          ;;
  *) 
	 COMMAND=$@
	 just_grep
         ;;
esac

