#!/bin/bash

grep_irn () {
   #echo "Running in grep_irn"
   #echo "$COMMAND"
   # TODO This will fail if given a relative path. Use readlink -f to get full path of file.
   #   May require another sed
   /usr/bin/grep -irn $COMMAND | sed 's/.*:[0-9]\+/file:& /' 
}

just_grep () {
  #echo "In just_grep"
  #echo "$COMMAND"
  /usr/bin/grep $COMMAND
}

FLAGS=$1
case "${FLAGS}" in
  -eliad*) 
	  shift
          COMMAND=$@
	  grep_irn
          ;;
  *) 
	 COMMAND=$@
	 just_grep
         ;;
esac

